name: eva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  dio: ^5.6.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.2 
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/