name: eva
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  dio: ^5.7.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.2 
  signature: ^5.5.0
  file_picker: ^8.1.2
  intl: ^0.19.0
  universal_html: ^2.2.4
  upgrader: ^10.3.0
  http: ^1.2.2
  package_info_plus: ^8.1.1
  connectivity_plus: ^6.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/logo_eva.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/