// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnydL4UyoyAqDzIjn-TBpHV8ejvnFW3I',
    appId: '1:236864918153:web:09250fc1b2381a0cf1ec58',
    messagingSenderId: '236864918153',
    projectId: 'eva-project-91804',
    authDomain: 'eva-project-91804.firebaseapp.com',
    storageBucket: 'eva-project-91804.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvwWaFajY6RFNIFW8jsBO-k690vRnZQiY',
    appId: '1:236864918153:android:041d29196514fac9f1ec58',
    messagingSenderId: '236864918153',
    projectId: 'eva-project-91804',
    storageBucket: 'eva-project-91804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAkbet2E9FnWcumImiSs3M7z-S3rr_i8',
    appId: '1:236864918153:ios:3915892179b05115f1ec58',
    messagingSenderId: '236864918153',
    projectId: 'eva-project-91804',
    storageBucket: 'eva-project-91804.appspot.com',
    iosBundleId: 'com.example.eva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAkbet2E9FnWcumImiSs3M7z-S3rr_i8',
    appId: '1:236864918153:ios:3915892179b05115f1ec58',
    messagingSenderId: '236864918153',
    projectId: 'eva-project-91804',
    storageBucket: 'eva-project-91804.appspot.com',
    iosBundleId: 'com.example.eva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUnydL4UyoyAqDzIjn-TBpHV8ejvnFW3I',
    appId: '1:236864918153:web:b0ddf850122c4ecaf1ec58',
    messagingSenderId: '236864918153',
    projectId: 'eva-project-91804',
    authDomain: 'eva-project-91804.firebaseapp.com',
    storageBucket: 'eva-project-91804.appspot.com',
  );
}
